# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cdeb5049a04b65f93e1889300a8724c4d5e5ba3b9d45085f5c90b23f637e5ec332f6586feca5be25e4d8453aec1e996c3e3c27bea16a0ed9baa20276b88f460

test:
  secret_key_base: 7ac2a74c296c6d0c8d15a68727d152b36386298d78e707f405c5a98b70252214cbdb714f008ae9d0f3a44035b395569cb91dde2b644b989532e474b4663cb970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
